const Action = {
	ADD_MESSAGE: "ADD-MESSAGE",
	UPDATE_MESSAGE: "UPDATE-MESSAGE",
	
	ADD_POST: "ADD-POST",
	UPDATE_POST: "UPDATE-POST",
	SET_USER_PROFILE: "SET-USER-PROFILE",
	
	SET_USERS: "SET-USERS",
	SET_PAGE_COUNT: "SET-PAGE-COUNT",
	SET_CURRENT_PAGE: "SET-CURRENT-PAGE",
	UPDATE_CURRENT_PAGE_ON_ARROWS: "UPDATE-CURRENT-PAGE-ON-ARROWS",
	TOGGLE_IS_FETCHING: "TOGGLE-IS-FETCHING",
	HIDE_LOADED_USERS: "HIDE-LOADED-USERS",

	LOGIN: "LOGIN",
	SET_USERNAME: "SET-USERNAME",
	SET_PASSWORD: "SET-PASSWORD",
}

export default Action;