const Action = {
	ADD_MESSAGE: "ADD-MESSAGE",
	UPDATE_MESSAGE: "UPDATE-MESSAGE",
	
	ADD_POST: "ADD-POST",
	UPDATE_POST: "UPDATE-POST",
	
	SET_USERS: "SET-USERS",
	SET_PAGE_SIZE: "SET-PAGE-SIZE",
	SET_PAGE_COUNT: "SET-PAGE-COUNT",
	SET_CURRENT_PAGE: "SET-CURRENT-PAGE",
	UPDATE_CURRENT_PAGE_ON_ARROWS: "UPDATE-CURRENT-PAGE-ON-ARROWS",
}

export default Action;